stages:
  - libs
  - build
  - deploy

libs:
  stage: libs
  script:
    - echo "Hello! npm install!"
  tags:
    - https://gitlab.dspace.kt.co.kr/

build:
  stage: build
  script:
    - echo "Hello! npm build!"
  tags:
    - https://gitlab.dspace.kt.co.kr/

deploy:
  stage: deploy
  script:
    - echo "Hello! npm deploy!"
  tags:
    - https://gitlab.dspace.kt.co.kr/
