stages:
  - libs
  - build
  - deploy

npm:
  stage: libs
  only:
    - dev
  script:
    - echo "Hello! npm install!"

build:
  stage: build
  only:
    - dev
  script:
    - echo "Hello! npm build!"

deploy:
  stage: deploy
  only:
    - dev
    - dev
  script:
    - echo "Hello! npm deploy!"
