export const menuItems = [
  {
    id: 1,
    label: "바로가기",
    subItems: [
      {
        id: 2,
        label: "홈",
        icon: "uil-home-alt",
        link: process.env.VUE_APP_PATH,
        parentId: 1,
      },
      {
        id: 3,
        label: "스팸메시지",
        icon: "uil-comment-alt-message",
        link: process.env.VUE_APP_SPAMLIST,
        parentId: 1,
      },
      {
        id: 4,
        label: "차단관리",
        icon: "uil-envelope-block",
        link: process.env.VUE_APP_SPAMBLOCKMANAGEMENT,
        parentId: 1,
      },
      {
        id: 5,
        label: "허용관리",
        icon: "uil-unlock-alt",
        link: process.env.VUE_APP_SPAMALLOWMANAGEMENT,
        parentId: 1,
      },
      {
        id: 6,
        label: "스팸신고",
        icon: "mdi mdi-alarm-light-outline",
        link: process.env.VUE_APP_SPAMREPORT,
        parentId: 1,
      },
    ],
  },
  {
    id: 10,
    label: "계정/설정관리",
    subItems: [
      {
        id: 11,
        label: "계정관리",
        icon: "uil-user",
        link: process.env.VUE_APP_IDENTIFY,
        parentId: 10,
      },
      {
        id: 12,
        label: "스마트차단",
        icon: "uil-lightbulb",
        link: process.env.VUE_APP_SMARTSETUP,
        parentId: 10,
      },
      {
        id: 13,
        label: "알림설정",
        icon: "uil-bright",
        link: process.env.VUE_APP_ALARMSETTING,
        parentId: 10,
      },
      {
        id: 14,
        label: "주소록동기화",
        icon: "uil-sync",
        link: process.env.VUE_APP_ADDRSYNC,
        parentId: 10,
      }
    ],
  },
  {
    id: 20,
    label: "고객지원",
    subItems: [
      {
        id: 21,
        label: "공지사항",
        icon: "uil-bell",
        link: process.env.VUE_APP_NOTICEPAGE,
        parentId: 20,
      },
      {
        id: 22,
        label: "이용안내",
        icon: "uil-notes",
        link: process.env.VUE_APP_USEINfO,
        parentId: 20,
      },
      {
        id: 23,
        label: "FAQ",
        icon: "uil-question-circle",
        link: process.env.VUE_APP_FAQPAGE,
        parentId: 20,
      },
      {
        id: 24,
        label: "1:1문의",
        icon: "uil-comments-alt",
        link: process.env.VUE_APP_PRIVATEREQUEST,
        parentId: 20,
      },
      {
        id: 25,
        label: "이메일 문의",
        icon: "uil-envelope",
        link: process.env.VUE_APP_EMAILREQUEST,
        parentId: 20,
      },
    ],
  },
  {
    id: 30,
    label: "정보",
    subItems: [
      {
        id: 31,
        label: "버전정보",
        icon: "uil-info-circle",
        link: process.env.VUE_APP_VERSION,
        parentId: 30,
      },
      {
        id: 32,
        label: "개인정보처리방침",
        icon: "uil-shield-check",
        link: process.env.VUE_APP_PRIVACYPOLICY,
        parentId: 30,
      },
      {
        id: 33,
        label: "오픈소스라이선스",
        icon: "uil-file-bookmark-alt",
        link: process.env.VUE_APP_OPENLICENSE,
        parentId: 30,
      },
      {
        id: 34,
        label: "선택약관 동의 변경",
        icon: "uil-file-edit-alt",
        link: process.env.VUE_APP_AGREEMENTTERMS,
        parentId: 30,
      },
      {
        id: 35,
        label: "앱 권한 이용 동의",
        icon: "uil-key-skeleton",
        link: process.env.VUE_APP_APPPERMISSION,
        parentId: 30,
      },
    ],
  },
];
